"""
Molecular feature analysis of the scBAC models.

This script reproduces two complementary analyses:

A. Genes associated with scBAC-predicted cellular age
   - analyzed separately for development and adult clocks;
   - training resource: donor-held-out OOF scBAC predictions;
   - independent multi-study validation: precomputed predictions generated by
     05_predict_scBAC_ensemble_fixed_pretrained.py;
   - Spearman correlation between log-normalized expression and predicted age;
   - training FDR < 0.05, validation P < 0.05, concordant direction;
   - top 100 genes by |Spearman r| per cell type for shared/unique analysis.

B. Model coefficient comparison
   - extract five-fold Elastic Net coefficients;
   - compare adult scBAC coefficients with the published Muralidharan human clock;
   - optionally compare glial scBAC coefficients with Buckley mouse clocks;
   - shared features require non-zero coefficients in both clocks with the same sign;
   - scBAC-specific features have non-zero scBAC coefficients but zero/absent
     coefficients in the comparison clock;
   - opposing signs are retained as a separate category, not as shared features.

GO Biological Process enrichment is performed in the companion R script:
07b_GO_enrichment.R
"""

# ============================================================================
# 1. IMPORT LIBRARIES
# ============================================================================

import os
import sys
import argparse
import joblib

import numpy as np
import pandas as pd
import scanpy as sc

from scipy import sparse
from scipy.stats import spearmanr
from statsmodels.stats.multitest import multipletests


# ============================================================================
# 2. PATHS AND ANALYSIS SETTINGS
# ============================================================================

PROJECT_ROOT = os.path.dirname(
    os.path.abspath(__file__)
)

DATA_DIR = os.path.join(
    PROJECT_ROOT,
    "dataset"
)

MODEL_ROOT = os.path.join(
    PROJECT_ROOT,
    "models"
)

SCBAC_MODEL_DIR = os.path.join(
    MODEL_ROOT,
    "full_genes_predictions_20260415"
)

ELASTICNET_MODEL_DIR = os.path.join(
    SCBAC_MODEL_DIR,
    "ElasticNet_Adult"
)

EVALUATION_DIR = os.path.join(
    PROJECT_ROOT,
    "results",
    "model_evaluation"
)

PREDICTION_DIR = os.path.join(
    PROJECT_ROOT,
    "results",
    "cell_age_predictions"
)

OUTPUT_DIR = os.path.join(
    PROJECT_ROOT,
    "results",
    "molecular_feature_analysis"
)

CORRELATION_DIR = os.path.join(
    OUTPUT_DIR,
    "predicted_cell_age_gene_correlations"
)

COEFFICIENT_DIR = os.path.join(
    OUTPUT_DIR,
    "ElasticNet_coefficients"
)

COMPARISON_DIR = os.path.join(
    OUTPUT_DIR,
    "clock_feature_comparisons"
)

GO_INPUT_DIR = os.path.join(
    OUTPUT_DIR,
    "GO_enrichment_input"
)

for directory in [
    OUTPUT_DIR,
    CORRELATION_DIR,
    COEFFICIENT_DIR,
    COMPARISON_DIR,
    GO_INPUT_DIR
]:
    os.makedirs(
        directory,
        exist_ok=True
    )

TRAIN_H5AD = os.path.join(
    DATA_DIR,
    "sce_train_CT.h5ad"
)

TRAIN_H5AD_OLD = os.path.join(
    DATA_DIR,
    "sce_train.h5ad"
)

NEW_2025_TRAINING_H5AD = os.path.join(
    DATA_DIR,
    "GSE291605_PFC.h5ad"
)

TRAIN_OOF_PREDICTION_FILE = os.path.join(
    EVALUATION_DIR,
    "Training_OOF_component_and_ensemble_predictions.csv.gz"
)

VALIDATION_H5AD = os.path.join(
    DATA_DIR,
    "sce_test.h5ad"
)

VALIDATION_PREDICTION_FILE = os.path.join(
    PREDICTION_DIR,
    "Integrated_Original_All_celltypes_full_life_genes_Models_Predictions.csv"
)

CELLTYPES = [
    "Exc",
    "Inh",
    "Ast",
    "Mic",
    "Oli",
    "OPC"
]

STAGES = [
    "development",
    "adult"
]

AGE_CUT = 18
DISCOVERY_FDR = 0.05
VALIDATION_P = 0.05
GENE_CHUNK_SIZE = 200
TOP_N_PER_CELLTYPE = 100

# ---------------------------------------------------------------------------
# Published-clock coefficient files
# ---------------------------------------------------------------------------

MURALIDHARAN_CLOCK_DIR = os.path.join(
    MODEL_ROOT,
    "benchmarking_model"
)

MURALIDHARAN_CLOCK_FILES = {
    celltype: os.path.join(
        MURALIDHARAN_CLOCK_DIR,
        "sc_{}.csv".format(celltype)
    )
    for celltype in CELLTYPES
}

BUCKLEY_CLOCK_DIR = os.path.join(
    DATA_DIR,
    "Buckley_mouse_clock_coefficients"
)

BUCKLEY_CLOCK_FILES = {
    celltype: os.path.join(
        BUCKLEY_CLOCK_DIR,
        "{}_clock_coefficients.csv".format(celltype)
    )
    for celltype in [
        "Ast",
        "Mic",
        "Oli",
        "OPC"
    ]
}

# The original coefficient analysis highlighted genes that were non-zero in all
# five Elastic Net folds. We export both strict and non-strict definitions.
# This setting controls which one is used for cross-clock feature classification.
COEFFICIENT_DEFINITION = "strict_consensus"


# ============================================================================
# OPTIONAL COMMAND-LINE PATH OVERRIDE
# ============================================================================

if __name__ == "__main__" and len(sys.argv) > 1:
    parser = argparse.ArgumentParser(
        description="Analyze genes and model coefficients associated with scBAC age."
    )

    parser.add_argument(
        "--training-h5ad",
        required=True
    )

    parser.add_argument(
        "--validation-h5ad",
        required=True
    )

    parser.add_argument(
        "--training-oof-predictions",
        required=True
    )

    parser.add_argument(
        "--validation-predictions",
        required=True
    )

    parser.add_argument(
        "--model-root",
        required=True,
        help="Root containing full_genes_predictions_20260415/ and benchmarking_model/."
    )

    parser.add_argument(
        "--output-dir",
        required=True
    )

    args = parser.parse_args()

    TRAIN_H5AD = args.training_h5ad
    VALIDATION_H5AD = args.validation_h5ad
    TRAIN_OOF_PREDICTION_FILE = args.training_oof_predictions
    VALIDATION_PREDICTION_FILE = args.validation_predictions
    MODEL_ROOT = os.path.abspath(
        args.model_root
    )
    SCBAC_MODEL_DIR = os.path.join(
        MODEL_ROOT,
        "full_genes_predictions_20260415"
    )
    ELASTICNET_MODEL_DIR = os.path.join(
        SCBAC_MODEL_DIR,
        "ElasticNet_Adult"
    )
    MURALIDHARAN_CLOCK_DIR = os.path.join(
        MODEL_ROOT,
        "benchmarking_model"
    )
    MURALIDHARAN_CLOCK_FILES = {
        celltype: os.path.join(
            MURALIDHARAN_CLOCK_DIR,
            "sc_{}.csv".format(celltype)
        )
        for celltype in CELLTYPES
    }

    OUTPUT_DIR = os.path.abspath(
        args.output_dir
    )

    CORRELATION_DIR = os.path.join(
        OUTPUT_DIR,
        "predicted_cell_age_gene_correlations"
    )

    COEFFICIENT_DIR = os.path.join(
        OUTPUT_DIR,
        "ElasticNet_coefficients"
    )

    COMPARISON_DIR = os.path.join(
        OUTPUT_DIR,
        "clock_feature_comparisons"
    )

    GO_INPUT_DIR = os.path.join(
        OUTPUT_DIR,
        "GO_enrichment_input"
    )

    for directory in [
        OUTPUT_DIR,
        CORRELATION_DIR,
        COEFFICIENT_DIR,
        COMPARISON_DIR,
        GO_INPUT_DIR
    ]:
        os.makedirs(
            directory,
            exist_ok=True
        )


# ============================================================================
# 3. HELPER FUNCTIONS FOR EXPRESSION-AGE CORRELATIONS
# ============================================================================


def normalize_adata(adata):
    adata = adata.copy()
    adata.X = adata.X.astype("float32")
    sc.pp.normalize_per_cell(
        adata
    )
    sc.pp.log1p(
        adata
    )
    return adata


def calculate_gene_correlations(
    adata,
    predicted_age,
    chunk_size=200
):
    """
    Calculate cell-level Spearman correlation for every gene in one cell type.

    Gene expression is processed in chunks to avoid converting the complete
    single-cell matrix to a dense array at once.
    """

    predicted_age = np.asarray(
        predicted_age,
        dtype=float
    )

    if len(predicted_age) != adata.n_obs:
        raise ValueError(
            "predicted_age length does not match AnnData cells"
        )

    result_rows = []

    for start in range(
        0,
        adata.n_vars,
        chunk_size
    ):
        stop = min(
            start + chunk_size,
            adata.n_vars
        )

        gene_names = adata.var_names[
            start:stop
        ].astype(str)

        X_chunk = adata[
            :,
            start:stop
        ].X

        if sparse.issparse(
            X_chunk
        ):
            X_chunk = X_chunk.toarray()
        else:
            X_chunk = np.asarray(
                X_chunk
            )

        for gene_index, gene in enumerate(
            gene_names
        ):
            expression = X_chunk[
                :,
                gene_index
            ]

            valid = (
                np.isfinite(
                    expression
                )
                & np.isfinite(
                    predicted_age
                )
            )

            if valid.sum() < 3:
                rho = np.nan
                p_value = np.nan
            elif np.std(
                expression[valid]
            ) == 0:
                rho = np.nan
                p_value = np.nan
            else:
                rho, p_value = spearmanr(
                    expression[valid],
                    predicted_age[valid]
                )

            result_rows.append(
                {
                    "gene": gene,
                    "spearman_rho": rho,
                    "p_value": p_value,
                    "n_cells": int(valid.sum())
                }
            )

        print(
            "  Genes {:,}-{:,.0f} / {:,}".format(
                start + 1,
                stop,
                adata.n_vars
            )
        )

    result_df = pd.DataFrame(
        result_rows
    )

    return result_df


def add_fdr(result_df):
    result_df = result_df.copy()
    result_df["fdr"] = np.nan

    valid = result_df["p_value"].notna()

    if valid.sum() > 0:
        result_df.loc[
            valid,
            "fdr"
        ] = multipletests(
            result_df.loc[
                valid,
                "p_value"
            ],
            method="fdr_bh"
        )[1]

    return result_df


def align_adata_and_predictions(
    adata,
    prediction_df,
    prediction_col
):
    """Align AnnData cells to a prediction table by cell ID."""

    prediction_df = prediction_df.copy()

    if "cell_id" in prediction_df.columns:
        prediction_df.index = prediction_df[
            "cell_id"
        ].astype(str)
    else:
        prediction_df.index = prediction_df.index.astype(str)

    adata_index = pd.Index(
        adata.obs_names.astype(str)
    )

    common_cells = adata_index.intersection(
        prediction_df.index
    )

    if len(common_cells) == 0:
        raise ValueError(
            "No common cell IDs were found between expression and predictions"
        )

    adata_use = adata[
        common_cells,
        :
    ].copy()

    prediction_use = prediction_df.loc[
        common_cells,
        :
    ].copy()

    return (
        adata_use,
        prediction_use,
        pd.to_numeric(
            prediction_use[prediction_col],
            errors="coerce"
        ).values
    )


# ============================================================================
# 4. LOAD TRAINING AND INDEPENDENT VALIDATION DATA
# ============================================================================

print("\n" + "=" * 70)
print("Loading expression and predicted-age data")
print("=" * 70)

if os.path.exists(TRAIN_H5AD):
    sce_train = sc.read_h5ad(
        TRAIN_H5AD
    )
else:
    sce_train_old = sc.read_h5ad(
        TRAIN_H5AD_OLD
    )

    sce_train_new = sc.read_h5ad(
        NEW_2025_TRAINING_H5AD
    )

    sce_train = sc.concat(
        [
            sce_train_old,
            sce_train_new
        ],
        axis=0,
        join="inner",
        merge="same",
        index_unique=None
    )

    if "status" in sce_train.obs.columns:
        sce_train = sce_train[
            sce_train.obs["status"] == "CT",
            :
        ].copy()

sce_validation = sc.read_h5ad(
    VALIDATION_H5AD
)

if "status" in sce_validation.obs.columns:
    sce_validation = sce_validation[
        sce_validation.obs["status"] == "CT",
        :
    ].copy()

training_predictions = pd.read_csv(
    TRAIN_OOF_PREDICTION_FILE
)

validation_predictions = pd.read_csv(
    VALIDATION_PREDICTION_FILE,
    index_col=0
)

training_predictions["cell_id"] = training_predictions[
    "cell_id"
].astype(str)

validation_predictions.index = validation_predictions.index.astype(str)

print(
    "Training expression:",
    sce_train.shape
)

print(
    "Validation expression:",
    sce_validation.shape
)


# ============================================================================
# 5. GENES ASSOCIATED WITH PREDICTED CELLULAR AGE
# ============================================================================

all_reproducible_results = []
all_top100_results = []

for stage in STAGES:

    print("\n" + "#" * 90)
    print("Predicted-cell-age gene analysis stage:", stage)
    print("#" * 90)

    if stage == "development":
        train_stage_mask = (
            pd.to_numeric(
                sce_train.obs["Age_at_death"],
                errors="coerce"
            )
            <= AGE_CUT
        )

        validation_stage_mask = (
            pd.to_numeric(
                sce_validation.obs["Age_at_death"],
                errors="coerce"
            )
            <= AGE_CUT
        )
    else:
        train_stage_mask = (
            pd.to_numeric(
                sce_train.obs["Age_at_death"],
                errors="coerce"
            )
            > AGE_CUT
        )

        validation_stage_mask = (
            pd.to_numeric(
                sce_validation.obs["Age_at_death"],
                errors="coerce"
            )
            > AGE_CUT
        )

    for celltype in CELLTYPES:

        print("\n" + "-" * 70)
        print("{} | {}".format(stage, celltype))
        print("-" * 70)

        # -------------------------------------------------------------------
        # 5.1 Training OOF analysis
        # -------------------------------------------------------------------

        train_mask = (
            train_stage_mask
            & (
                sce_train.obs["celltype"].astype(str)
                == celltype
            )
        )

        adata_train_ct = sce_train[
            train_mask,
            :
        ].copy()

        train_pred_ct = training_predictions[
            (training_predictions["stage"].astype(str) == stage)
            & (
                training_predictions["celltype_model"].astype(str)
                == celltype
            )
        ].copy()

        adata_train_ct, train_pred_ct, train_pred_age = align_adata_and_predictions(
            adata_train_ct,
            train_pred_ct,
            "scBAC_oof_prediction"
        )

        adata_train_ct = normalize_adata(
            adata_train_ct
        )

        training_result = calculate_gene_correlations(
            adata_train_ct,
            train_pred_age,
            chunk_size=GENE_CHUNK_SIZE
        )

        training_result = add_fdr(
            training_result
        )

        training_result["celltype"] = celltype
        training_result["stage"] = stage

        training_result.to_csv(
            os.path.join(
                CORRELATION_DIR,
                "{}_{}_training_OOF_gene_correlations.csv".format(
                    stage,
                    celltype
                )
            ),
            index=False
        )

        # -------------------------------------------------------------------
        # 5.2 Independent validation analysis
        # -------------------------------------------------------------------

        validation_mask = (
            validation_stage_mask
            & (
                sce_validation.obs["celltype"].astype(str)
                == celltype
            )
        )

        adata_validation_ct = sce_validation[
            validation_mask,
            :
        ].copy()

        validation_pred_ct = validation_predictions[
            validation_predictions["celltype"].astype(str)
            == celltype
        ].copy()

        # The fixed prediction script writes the development/adult routed ensemble
        # prediction as Ensemble_adult_deve. Because the expression data are already
        # split by stage above, this is equivalent to using Ensemble_Development for
        # <=18 years and Ensemble_Adult for >18 years.
        adata_validation_ct, validation_pred_ct, validation_pred_age = align_adata_and_predictions(
            adata_validation_ct,
            validation_pred_ct,
            "Ensemble_adult_deve"
        )

        adata_validation_ct = normalize_adata(
            adata_validation_ct
        )

        validation_result = calculate_gene_correlations(
            adata_validation_ct,
            validation_pred_age,
            chunk_size=GENE_CHUNK_SIZE
        )

        validation_result["celltype"] = celltype
        validation_result["stage"] = stage

        validation_result.to_csv(
            os.path.join(
                CORRELATION_DIR,
                "{}_{}_independent_validation_gene_correlations.csv".format(
                    stage,
                    celltype
                )
            ),
            index=False
        )

        # -------------------------------------------------------------------
        # 5.3 Reproducible genes
        # -------------------------------------------------------------------

        merged = training_result.merge(
            validation_result[
                [
                    "gene",
                    "spearman_rho",
                    "p_value"
                ]
            ],
            on="gene",
            how="inner",
            suffixes=(
                "_training",
                "_validation"
            )
        )

        reproducible = merged[
            (merged["fdr"] < DISCOVERY_FDR)
            & (merged["p_value_validation"] < VALIDATION_P)
            & (
                np.sign(
                    merged["spearman_rho_training"]
                )
                == np.sign(
                    merged["spearman_rho_validation"]
                )
            )
        ].copy()

        reproducible["celltype"] = celltype
        reproducible["stage"] = stage
        reproducible["abs_rho_training"] = reproducible[
            "spearman_rho_training"
        ].abs()

        reproducible["direction"] = np.where(
            reproducible["spearman_rho_training"] > 0,
            "Positive",
            "Negative"
        )

        all_reproducible_results.append(
            reproducible
        )

        # Top 100 reproducible genes in each cell type by absolute training rho
        top100 = reproducible.sort_values(
            "abs_rho_training",
            ascending=False
        ).head(
            TOP_N_PER_CELLTYPE
        ).copy()

        top100["rank"] = np.arange(
            1,
            top100.shape[0] + 1
        )

        all_top100_results.append(
            top100
        )

        print(
            "Reproducible genes:",
            reproducible.shape[0]
        )

        del adata_train_ct
        del adata_validation_ct


# ============================================================================
# 6. SAVE REPRODUCIBLE AND TOP-100 GENE RESULTS
# ============================================================================

reproducible_cell_age_genes = pd.concat(
    all_reproducible_results,
    axis=0,
    ignore_index=True
)

reproducible_cell_age_genes.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "reproducible_predicted_cell_age_associated_genes.csv"
    ),
    index=False
)

top100_cell_age_genes = pd.concat(
    all_top100_results,
    axis=0,
    ignore_index=True
)

top100_cell_age_genes.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "top100_predicted_cell_age_genes_per_celltype.csv"
    ),
    index=False
)


# ============================================================================
# 7. SHARED AND CELL-TYPE-SPECIFIC TOP-100 GENES
# ============================================================================

shared_unique_rows = []

for stage in STAGES:

    stage_top = top100_cell_age_genes[
        top100_cell_age_genes["stage"] == stage
    ].copy()

    gene_celltype_count = (
        stage_top.groupby(
            "gene"
        )["celltype"]
        .nunique()
    )

    for _, row in stage_top.iterrows():

        n_celltypes = int(
            gene_celltype_count.loc[
                row["gene"]
            ]
        )

        shared_unique_rows.append(
            {
                "stage": stage,
                "celltype": row["celltype"],
                "gene": row["gene"],
                "rank": row["rank"],
                "spearman_rho_training": row["spearman_rho_training"],
                "n_celltypes_in_top100": n_celltypes,
                "classification": (
                    "Cell-type-specific"
                    if n_celltypes == 1
                    else "Shared"
                )
            }
        )

shared_unique_top100 = pd.DataFrame(
    shared_unique_rows
)

shared_unique_top100.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "top100_shared_and_celltype_specific_genes.csv"
    ),
    index=False
)

# Export gene sets for GO enrichment
for (stage, classification), group_df in shared_unique_top100.groupby(
    [
        "stage",
        "classification"
    ],
    observed=True
):

    genes = sorted(
        group_df["gene"].dropna().unique()
    )

    pd.DataFrame(
        {
            "gene": genes
        }
    ).to_csv(
        os.path.join(
            GO_INPUT_DIR,
            "predicted_age_{}_{}_genes.csv".format(
                stage,
                classification.replace(
                    "-",
                    "_"
                ).replace(
                    " ",
                    "_"
                )
            )
        ),
        index=False
    )


# ============================================================================
# 8. EXTRACT FIVE-FOLD ELASTIC NET COEFFICIENTS
# ============================================================================

print("\n" + "=" * 70)
print("Extracting Elastic Net model coefficients")
print("=" * 70)


def extract_elasticnet_coefficients(
    model_dir,
    celltype,
    age_cut=18,
    n_features=12779
):
    """Extract all five fold weights from the fixed public Elastic Net ensemble."""

    feature_file = os.path.join(
        model_dir,
        "model_features",
        "{}_elasticnet_features_age_cut{}_n_features{}.csv".format(
            celltype,
            age_cut,
            n_features
        )
    )

    model_file = os.path.join(
        model_dir,
        "{}_elasticnet_5fold_ensemble_age_cut{}_n_features{}.pkl".format(
            celltype,
            age_cut,
            n_features
        )
    )

    if not os.path.exists(feature_file):
        raise FileNotFoundError(feature_file)

    if not os.path.exists(model_file):
        raise FileNotFoundError(model_file)

    feature_table = pd.read_csv(
        feature_file
    )

    if "genename" not in feature_table.columns:
        raise KeyError(
            "Expected a 'genename' column in {}".format(
                feature_file
            )
        )

    features = feature_table[
        "genename"
    ].astype(str).values

    models = joblib.load(
        model_file
    )

    if not isinstance(models, (list, tuple)):
        models = [models]

    if len(models) != 5:
        raise ValueError(
            "Expected exactly five Elastic Net fold models for {}, found {}".format(
                celltype,
                len(models)
            )
        )

    result = pd.DataFrame(
        {
            "gene": features
        }
    )

    intercepts = []

    for fold_idx, model in enumerate(
        models,
        start=1
    ):
        if len(model.coef_) != len(features):
            raise ValueError(
                "Feature/coefficient length mismatch for {} fold {}: {} genes vs {} coefficients".format(
                    celltype,
                    fold_idx,
                    len(features),
                    len(model.coef_)
                )
            )

        result[
            "fold_{}_weight".format(
                fold_idx
            )
        ] = model.coef_

        intercepts.append(
            float(
                model.intercept_
            )
        )

    fold_columns = [
        "fold_{}_weight".format(i)
        for i in range(
            1,
            6
        )
    ]

    result["mean_weight"] = result[
        fold_columns
    ].mean(
        axis=1
    )

    result["non_zero_fold_count"] = (
        result[
            fold_columns
        ]
        != 0
    ).sum(
        axis=1
    )

    result["strict_consensus_mean_weight"] = np.where(
        result["non_zero_fold_count"] == len(models),
        result["mean_weight"],
        np.nan
    )

    result["any_fold_nonzero"] = (
        result["non_zero_fold_count"] > 0
    )

    result["strict_5fold_nonzero"] = (
        result["non_zero_fold_count"] == len(models)
    )

    intercept_info = pd.DataFrame(
        {
            "fold": np.arange(
                1,
                len(models) + 1
            ),
            "intercept": intercepts
        }
    )

    return result, intercept_info


adult_elasticnet_coefficients = {}

for celltype in CELLTYPES:

    model_file = os.path.join(
        ELASTICNET_MODEL_DIR,
        "{}_elasticnet_5fold_ensemble_age_cut18_n_features12779.pkl".format(
            celltype
        )
    )

    feature_file = os.path.join(
        ELASTICNET_MODEL_DIR,
        "model_features",
        "{}_elasticnet_features_age_cut18_n_features12779.csv".format(
            celltype
        )
    )

    if not os.path.exists(model_file) or not os.path.exists(feature_file):
        print(
            "Missing fixed adult Elastic Net model for",
            celltype
        )
        continue

    coefficient_df, intercept_df = extract_elasticnet_coefficients(
        ELASTICNET_MODEL_DIR,
        celltype=celltype,
        age_cut=18,
        n_features=12779
    )

    coefficient_df["celltype"] = celltype

    coefficient_df.to_csv(
        os.path.join(
            COEFFICIENT_DIR,
            "{}_adult_ElasticNet_five_fold_coefficients.csv".format(
                celltype
            )
        ),
        index=False
    )

    intercept_df.to_csv(
        os.path.join(
            COEFFICIENT_DIR,
            "{}_adult_ElasticNet_intercepts.csv".format(
                celltype
            )
        ),
        index=False
    )

    adult_elasticnet_coefficients[
        celltype
    ] = coefficient_df


# ============================================================================
# 9. READ A PUBLISHED CLOCK COEFFICIENT TABLE
# ============================================================================


def read_published_clock_coefficients(
    clock_file,
    feature_col="clock feature (intercept or gene)",
    intercept_label="intercept"
):
    """Return one mean gene coefficient per feature from a published clock CSV."""

    clock_df = pd.read_csv(
        clock_file
    )

    # Support a few common public-table gene column names
    if feature_col not in clock_df.columns:
        gene_candidates = [
            col
            for col in clock_df.columns
            if str(col).lower() in [
                "gene",
                "genename",
                "feature",
                "clock_feature"
            ]
        ]

        if len(gene_candidates) == 0:
            raise KeyError(
                "No feature/gene column found in {}".format(
                    clock_file
                )
            )

        feature_col = gene_candidates[0]

    coefficient_cols = [
        col
        for col in clock_df.columns
        if "Fold" in str(col)
    ]

    if len(coefficient_cols) == 0:
        coefficient_cols = [
            col
            for col in clock_df.columns
            if str(col).lower() in [
                "coefficient",
                "coef",
                "weight"
            ]
        ]

    if len(coefficient_cols) == 0:
        raise KeyError(
            "No coefficient columns found in {}".format(
                clock_file
            )
        )

    gene_df = clock_df[
        clock_df[feature_col].astype(str)
        != intercept_label
    ].copy()

    for col in coefficient_cols:
        gene_df[col] = pd.to_numeric(
            gene_df[col],
            errors="coerce"
        ).fillna(0)

    result = pd.DataFrame(
        {
            "gene": gene_df[
                feature_col
            ].astype(str).values,
            "comparison_weight": gene_df[
                coefficient_cols
            ].mean(
                axis=1
            ).values
        }
    )

    return result


# ============================================================================
# 10. COMPARE SCBAC ELASTIC NET WITH PUBLISHED CLOCKS
# ============================================================================


def compare_clock_features(
    scbac_df,
    comparison_df,
    comparison_name,
    coefficient_definition="strict_consensus"
):
    """Classify shared, scBAC-specific, comparison-specific, and opposite-sign genes."""

    if coefficient_definition == "strict_consensus":
        scbac_use = scbac_df[
            [
                "gene",
                "strict_consensus_mean_weight"
            ]
        ].rename(
            columns={
                "strict_consensus_mean_weight": "scBAC_weight"
            }
        )
    elif coefficient_definition == "any_fold":
        scbac_use = scbac_df[
            [
                "gene",
                "mean_weight",
                "any_fold_nonzero"
            ]
        ].copy()

        scbac_use["scBAC_weight"] = np.where(
            scbac_use["any_fold_nonzero"],
            scbac_use["mean_weight"],
            0.0
        )

        scbac_use = scbac_use[
            [
                "gene",
                "scBAC_weight"
            ]
        ]
    else:
        raise ValueError(
            "coefficient_definition must be 'strict_consensus' or 'any_fold'"
        )

    merged = scbac_use.merge(
        comparison_df,
        on="gene",
        how="outer"
    )

    merged["scBAC_weight"] = merged[
        "scBAC_weight"
    ].fillna(0.0)

    merged["comparison_weight"] = merged[
        "comparison_weight"
    ].fillna(0.0)

    scbac_nonzero = merged[
        "scBAC_weight"
    ].ne(0)

    comparison_nonzero = merged[
        "comparison_weight"
    ].ne(0)

    same_sign = (
        np.sign(
            merged["scBAC_weight"]
        )
        == np.sign(
            merged["comparison_weight"]
        )
    )

    merged["feature_class"] = "Neither"

    merged.loc[
        scbac_nonzero
        & comparison_nonzero
        & same_sign,
        "feature_class"
    ] = "Shared_same_sign"

    merged.loc[
        scbac_nonzero
        & ~comparison_nonzero,
        "feature_class"
    ] = "scBAC_specific"

    merged.loc[
        ~scbac_nonzero
        & comparison_nonzero,
        "feature_class"
    ] = "Comparison_specific"

    merged.loc[
        scbac_nonzero
        & comparison_nonzero
        & ~same_sign,
        "feature_class"
    ] = "Opposite_sign"

    merged["comparison_clock"] = comparison_name

    return merged


for celltype, scbac_coefficients in adult_elasticnet_coefficients.items():

    # -----------------------------------------------------------------------
    # 10.1 Muralidharan human clock
    # -----------------------------------------------------------------------

    muralidharan_file = MURALIDHARAN_CLOCK_FILES.get(
        celltype
    )

    if (
        muralidharan_file is not None
        and os.path.exists(
            muralidharan_file
        )
    ):
        muralidharan_coefficients = read_published_clock_coefficients(
            muralidharan_file
        )

        comparison = compare_clock_features(
            scbac_coefficients,
            muralidharan_coefficients,
            comparison_name="Muralidharan",
            coefficient_definition=COEFFICIENT_DEFINITION
        )

        comparison["celltype"] = celltype

        comparison.to_csv(
            os.path.join(
                COMPARISON_DIR,
                "{}_scBAC_vs_Muralidharan_features.csv".format(
                    celltype
                )
            ),
            index=False
        )

        for feature_class in [
            "Shared_same_sign",
            "scBAC_specific"
        ]:
            gene_list = comparison.loc[
                comparison["feature_class"] == feature_class,
                "gene"
            ].dropna().unique()

            pd.DataFrame(
                {
                    "gene": sorted(
                        gene_list
                    )
                }
            ).to_csv(
                os.path.join(
                    GO_INPUT_DIR,
                    "{}_Muralidharan_{}_genes.csv".format(
                        celltype,
                        feature_class
                    )
                ),
                index=False
            )

    # -----------------------------------------------------------------------
    # 10.2 Buckley mouse glial clocks
    # -----------------------------------------------------------------------

    buckley_file = BUCKLEY_CLOCK_FILES.get(
        celltype
    )

    if (
        buckley_file is not None
        and os.path.exists(
            buckley_file
        )
    ):
        buckley_coefficients = read_published_clock_coefficients(
            buckley_file
        )

        comparison = compare_clock_features(
            scbac_coefficients,
            buckley_coefficients,
            comparison_name="Buckley_mouse",
            coefficient_definition=COEFFICIENT_DEFINITION
        )

        comparison["celltype"] = celltype

        comparison.to_csv(
            os.path.join(
                COMPARISON_DIR,
                "{}_scBAC_vs_Buckley_mouse_features.csv".format(
                    celltype
                )
            ),
            index=False
        )

        for feature_class in [
            "Shared_same_sign",
            "scBAC_specific"
        ]:
            gene_list = comparison.loc[
                comparison["feature_class"] == feature_class,
                "gene"
            ].dropna().unique()

            pd.DataFrame(
                {
                    "gene": sorted(
                        gene_list
                    )
                }
            ).to_csv(
                os.path.join(
                    GO_INPUT_DIR,
                    "{}_Buckley_mouse_{}_genes.csv".format(
                        celltype,
                        feature_class
                    )
                ),
                index=False
            )


# ============================================================================
# 11. SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("Molecular feature analysis complete")
print("=" * 70)

print(
    "Reproducible predicted-age genes:",
    reproducible_cell_age_genes.shape[0]
)

print(
    "Top-100 shared/unique table:",
    shared_unique_top100.shape
)

print(
    "GO input directory:",
    GO_INPUT_DIR
)


# ============================================================================
# 12. COMMAND-LINE USAGE
# ============================================================================

"""
python 07_scBAC_molecular_feature_analysis.py \
    --training-h5ad /path/to/sce_train_CT.h5ad \
    --validation-h5ad /path/to/sce_test.h5ad \
    --training-oof-predictions /path/to/Training_OOF_component_and_ensemble_predictions.csv.gz \
    --validation-predictions /path/to/Integrated_Original_All_celltypes_full_life_genes_Models_Predictions.csv \
    --model-root /path/to/models \
    --output-dir /path/to/results/molecular_feature_analysis
"""
