"""
Effects of neurodegenerative diseases on scBAC-predicted cellular age.

Analyses retained from the final Methods:
- study-matched cell-level NDD effects across tissue x cell type (OLS)
- donor-median AD effect in ROSMAP PFC and SEAAD+GSE263468 PFC replication
- AD odds per 1-SD donor-median cellular-age increase
- associations with Braak/CERAD/cognition among AD donors
- AD effects and clinicopathological associations across 13 Inh subtypes
- SST molecular signature: AD differential expression intersected with genes associated
  with donor-median SST cellular age

Historical mixed-model and sensitivity-analysis blocks are intentionally omitted.
"""

from pathlib import Path
import os
import numpy as np
import pandas as pd
import scanpy as sc

from downstream_analysis_utils import (
    MAIN_CELLTYPES, add_scbac_adult, make_donor_uid, donor_median_summary,
    run_ndd_cellular_age_ols, run_donor_ad_age_ols, run_ad_odds_logistic,
    run_pathology_associations, bh_fdr, normalize_log1p,
)
from scipy.stats import spearmanr

# =============================================================================
# 1. CONFIGURATION
# =============================================================================
PROJECT_ROOT = Path(
    ""
)

DATA_DIR = PROJECT_ROOT / "dataset"

RESULT_DIR = PROJECT_ROOT / "results" / "NDD_cellular_aging"
RESULT_DIR.mkdir(parents=True, exist_ok=True)


MAIN_METADATA = DATA_DIR / "meta_human_cortex_scrna_atlas_CT_NDDs.csv"
ALS_FTLD_METADATA = DATA_DIR / "meta_ALS_FTLD.csv"
SEAAD_METADATA = DATA_DIR / "meta_SEAAD_PFC_replication.csv"
GSE263468_METADATA = DATA_DIR / "meta_GSE263468_PFC_AD_replication.csv"

# Optional Inh-subtype metadata generated by script 09 or the manuscript working set.
ROSMAP_INH_METADATA = DATA_DIR / "meta_ROSMAC_PFC_Inh_Subclass_discovery.csv"
SEAAD_INH_METADATA = DATA_DIR / "meta_SEAAD_PFC_Inh_Subclass_replication.csv"
GSE263468_INH_METADATA = DATA_DIR / "meta_GSE263468_Inh_Subclass_replication.csv"
SUBTYPE_COL = "sub_celltype_celltypist_raw"  # change to your final 13-subtype column if needed

# Optional expression matrices for the SST molecular analysis.
ROSMAP_EXPRESSION = DATA_DIR / "sce_test.h5ad"
SEAAD_EXPRESSION = DATA_DIR / "SEAAD_A9_RNAseq_final-nuclei.2024-02-13.h5ad"
GSE263468_EXPRESSION = DATA_DIR / "GSE263468_PFC_processed_CellXGene.h5ad"
RUN_SST_GENE_ANALYSIS = False

NDD_LABELS = ["AD", "MCI", "PD", "FTD", "FTLD", "ALS"]

# =============================================================================
# 2. LOAD AND HARMONIZE CELL-LEVEL METADATA
# =============================================================================
meta = pd.read_csv(MAIN_METADATA, index_col=0)
if ALS_FTLD_METADATA.exists():
    meta = pd.concat([meta, pd.read_csv(ALS_FTLD_METADATA, index_col=0)], axis=0)


    
meta = meta[meta["status"].astype(str) != "Dementia"].copy()
meta["sub_tissue"] = meta["sub_tissue"].replace({
    "Midtemporal": "Temporal cortex",
    "Primary-motor-cortex": "Primary motor cortex",
})
meta = meta[meta["celltype"].isin(MAIN_CELLTYPES)].copy()
meta = add_scbac_adult(meta)
meta = make_donor_uid(meta)

# =============================================================================
# 3. STUDY-MATCHED NDD CELL-LEVEL EFFECTS
# =============================================================================
ndd_results = []
for disease in NDD_LABELS:
    disease_studies = meta.loc[meta["status"].astype(str) == disease, "dataset"].dropna().unique()
    if len(disease_studies) == 0:
        continue
    d = meta[meta["dataset"].isin(disease_studies)].copy()
    # Prevent cross-contamination between the two disease labels in shared resources.
    if disease == "FTLD":
        d = d[d["status"] != "ALS"]
    if disease == "ALS":
        d = d[d["status"] != "FTLD"]
    d = d[d["status"].isin(["CT", disease])].copy()
    res = run_ndd_cellular_age_ols(d, disease_label=disease, outcome_col="scBAC_adult")
    if not res.empty:
        ndd_results.append(res)
        res.to_csv(RESULT_DIR / f"{disease}_cellular_age_effects.csv", index=False)

if ndd_results:
    pd.concat(ndd_results, ignore_index=True).to_csv(
        RESULT_DIR / "all_NDD_cellular_age_effects.csv", index=False
    )

# =============================================================================
# 4. DONOR-LEVEL AD DISCOVERY / REPLICATION
# =============================================================================
def prepare_ad_resource(df, resource_name):
    d = df.copy()
    d = d[d["celltype"].isin(MAIN_CELLTYPES)]
    d = d[d["status"].isin(["CT", "AD"])]
    d = d[d["sub_tissue"].astype(str) == "Prefrontal cortex"]
    d = add_scbac_adult(d)
    d = make_donor_uid(d)
    d["resource"] = resource_name
    return d

# Discovery is exactly ROSMAP PFC.
dis_cells = prepare_ad_resource(meta[meta["dataset"].astype(str) == "ROSMAP.MIT"], "Discovery")

# Primary replication is exactly SEAAD + GSE263468 PFC.
rep_parts = []
for path in [SEAAD_METADATA, GSE263468_METADATA]:
    if path.exists():
        rep_parts.append(pd.read_csv(path, index_col=0))


        
if rep_parts:
    rep_cells = prepare_ad_resource(pd.concat(rep_parts, axis=0), "Replication")
else:
    rep_cells = pd.DataFrame()



metadata_cols = ["status", "sub_tissue", "Sex", "Age_at_death", "PMI"]
dis_donor = donor_median_summary(dis_cells, ["scBAC_adult"], metadata_cols=metadata_cols)
rep_donor = donor_median_summary(rep_cells, ["scBAC_adult"], metadata_cols=metadata_cols) if not rep_cells.empty else pd.DataFrame()

dis_donor.to_csv(RESULT_DIR / "AD_discovery_donor_median_cellular_age.csv", index=False)
if not rep_donor.empty:
    rep_donor.to_csv(RESULT_DIR / "AD_replication_donor_median_cellular_age.csv", index=False)



for name, donor_df in [("discovery", dis_donor), ("replication", rep_donor)]:
    if donor_df.empty:
        continue
    run_donor_ad_age_ols(donor_df).to_csv(RESULT_DIR / f"AD_{name}_donor_age_effect.csv", index=False)
    run_ad_odds_logistic(donor_df).to_csv(RESULT_DIR / f"AD_{name}_odds_per_1SD_cellular_age.csv", index=False)

# =============================================================================
# 5. AD PATHOLOGY / COGNITION
# =============================================================================
def attach_donor_phenotypes(donor_df, cell_df, columns):
    if donor_df.empty:
        return donor_df
    first = cell_df.drop_duplicates("donor_uid").set_index("donor_uid")
    keep = [c for c in columns if c in first.columns]
    out = donor_df.copy()
    for col in keep:
        out[col] = out["donor_uid"].map(first[col])
    return out

# Discovery: Braak, CERAD and reverse-coded MMSE quartile (higher = worse cognition).
dis_path = attach_donor_phenotypes(dis_donor, dis_cells, ["Braak_stage", "ceradsc", "MMSE"])
dis_path = dis_path[dis_path["status"] == "AD"].copy()
if "MMSE" in dis_path.columns:
    mmse_numeric = pd.to_numeric(dis_path["MMSE"], errors="coerce")
    valid = mmse_numeric.notna()
    if valid.sum() >= 4:
        try:
            q = pd.qcut(mmse_numeric[valid], q=4, labels=[4, 3, 2, 1], duplicates="drop")
            dis_path.loc[valid, "MMSE_impairment_quartile"] = pd.to_numeric(q, errors="coerce")
        except ValueError:
            pass


            
dis_pheno = [c for c in ["Braak_stage", "ceradsc", "MMSE_impairment_quartile"] if c in dis_path.columns]
if dis_pheno:
    run_pathology_associations(dis_path, dis_pheno).to_csv(
        RESULT_DIR / "AD_discovery_pathology_cognition_associations.csv", index=False
    )


# Replication: harmonize Braak, CERAD and cognitive status.
if not rep_donor.empty:
    rep_path = attach_donor_phenotypes(rep_donor, rep_cells, ["Braak_stage", "CERAD score", "Cognitive Status"])
    rep_path = rep_path[rep_path["status"] == "AD"].copy()
    if "Braak_stage" in rep_path.columns:
        braak_map = {"Braak 0": 0, "Braak I": 1, "Braak II": 2, "Braak III": 3, "Braak IV": 4, "Braak V": 5, "Braak VI": 6}
        rep_path["Braak_numeric"] = rep_path["Braak_stage"].replace(braak_map)
    if "CERAD score" in rep_path.columns:
        rep_path["CERAD_numeric"] = rep_path["CERAD score"].map({"Frequent": 1.0, "Moderate": 2.0, "Sparse": 3.0, "Absent": 4.0})
    if "Cognitive Status" in rep_path.columns:
        rep_path["Cognitive_impairment"] = rep_path["Cognitive Status"].map({"Dementia": 1.0, "No dementia": 0.0})
    rep_pheno = [c for c in ["Braak_numeric", "CERAD_numeric", "Cognitive_impairment"] if c in rep_path.columns]
    if rep_pheno:
        run_pathology_associations(rep_path, rep_pheno).to_csv(
            RESULT_DIR / "AD_replication_pathology_cognition_associations.csv", index=False
        )

# =============================================================================
# 6. INHIBITORY-NEURON SUBTYPE AD EFFECTS
# =============================================================================
def load_subtype_metadata(paths, resource):
    parts = []
    for path in paths:
        if Path(path).exists():
            x = pd.read_csv(path, index_col=0)
            x["resource"] = resource
            parts.append(x)
    if not parts:
        return pd.DataFrame()
    d = pd.concat(parts, axis=0)
    d = add_scbac_adult(d)
    d = make_donor_uid(d)
    # Backward compatibility with working metadata.
    if SUBTYPE_COL not in d.columns:
        for candidate in ["sub_celltype2", "sub_celltype_celltypist", "sub_celltype_celltypist_coarse"]:
            if candidate in d.columns:
                d[SUBTYPE_COL] = d[candidate]
                break
    return d

sub_dis = load_subtype_metadata([ROSMAP_INH_METADATA], "Discovery")
sub_rep = load_subtype_metadata([SEAAD_INH_METADATA, GSE263468_INH_METADATA], "Replication")
sub_rep = sub_rep[sub_rep['sub_tissue']=='Prefrontal cortex'].copy()
for name, cells in [("discovery", sub_dis), ("replication", sub_rep)]:
    if cells.empty or SUBTYPE_COL not in cells.columns:
        continue
    d = cells[cells["status"].isin(["CT", "AD"])].copy()
    # Treat subtype as the analysis cell-type variable and summarize by donor.
    tmp = d.rename(columns={SUBTYPE_COL: "analysis_subtype"})
    donor = donor_median_summary(
        tmp, ["scBAC_adult"], celltype_col="analysis_subtype",
        metadata_cols=["status", "Sex", "Age_at_death", "PMI", "dataset", "sub_tissue"]
    )
    effect = run_donor_ad_age_ols(donor, celltype_col="analysis_subtype")
    effect.rename(columns={"CellType": "Inh_Subtype"}).to_csv(
        RESULT_DIR / f"AD_{name}_Inh_subtype_cellular_age_effect.csv", index=False
    )

# =============================================================================
# 7. OPTIONAL SST MOLECULAR SIGNATURE
# =============================================================================
# The working script contained a large collection of exploratory gene blocks. The
# final analysis needs only the intersection of AD DE with donor-level SST age
# association. This section is optional because raw expression resource paths vary.

def sst_gene_analysis(adata, metadata, subtype_col, label="Inh SST"):
    ids = adata.obs_names.intersection(metadata.index)
    a = adata[ids].copy()
    m = metadata.loc[ids].copy()
    for col in m.columns:
        a.obs[col] = m[col].values
    a = a[(a.obs[subtype_col].astype(str) == label) & a.obs["status"].isin(["CT", "AD"])].copy()
    if a.n_obs == 0:
        return pd.DataFrame()
    a = normalize_log1p(a)
    sc.tl.rank_genes_groups(a, "status", groups=["AD"], reference="CT", method="wilcoxon", pts=True)
    deg = sc.get.rank_genes_groups_df(a, group="AD").rename(columns={"names": "gene", "logfoldchanges": "AD_log2FC", "pvals": "AD_P", "pvals_adj": "AD_FDR"})

    # donor pseudobulk expression and donor-median SST cellular age
    donor_key = "donor_uid" if "donor_uid" in a.obs.columns else "donor_id"
    donor_age = a.obs.groupby(donor_key, observed=True)["scBAC_adult"].median()
    rows = []
    for gene in a.var_names:
        values = []
        ages = []
        for donor, idx in a.obs.groupby(donor_key, observed=True).indices.items():
            block = a[idx, gene].X
            x = float(np.asarray(block.mean()).reshape(-1)[0])
            values.append(x); ages.append(donor_age.loc[donor])
        if len(values) >= 5 and np.std(values) > 0:
            rho, p = spearmanr(values, ages)
            rows.append({"gene": str(gene), "age_spearman_rho": rho, "age_P": p})
    corr = pd.DataFrame(rows)
    if not corr.empty:
        corr["age_FDR"] = bh_fdr(corr["age_P"])
    out = deg.merge(corr, on="gene", how="inner")
    out["aging_consistent"] = ((out["AD_log2FC"] > 0) & (out["age_spearman_rho"] > 0)) | ((out["AD_log2FC"] < 0) & (out["age_spearman_rho"] < 0))
    return out

if RUN_SST_GENE_ANALYSIS:
    dis_gene = pd.DataFrame()
    rep_gene = pd.DataFrame()
    if ROSMAP_EXPRESSION.exists() and not sub_dis.empty:
        a = sc.read_h5ad(ROSMAP_EXPRESSION)
        dis_gene = sst_gene_analysis(a, sub_dis, SUBTYPE_COL)
        dis_gene.to_csv(RESULT_DIR / "SST_AD_aging_genes_discovery.csv", index=False)

    # Build the combined SEAAD + GSE263468 replication expression resource.
    rep_adatas = []
    rep_meta_parts = []
    for expr_path, meta_path in [(SEAAD_EXPRESSION, SEAAD_INH_METADATA), (GSE263468_EXPRESSION, GSE263468_INH_METADATA)]:
        if expr_path.exists() and meta_path.exists():
            m = pd.read_csv(meta_path, index_col=0)
            a = sc.read_h5ad(expr_path)
            ids = a.obs_names.intersection(m.index.astype(str))
            if len(ids):
                rep_adatas.append(a[ids].copy())
                rep_meta_parts.append(m.loc[ids])
    if rep_adatas:
        rep_expr = sc.concat(rep_adatas, axis=0, join="inner", merge="same", index_unique=None)
        rep_meta = pd.concat(rep_meta_parts, axis=0)
        rep_gene = sst_gene_analysis(rep_expr, rep_meta, SUBTYPE_COL)
        rep_gene.to_csv(RESULT_DIR / "SST_AD_aging_genes_replication.csv", index=False)

    if not dis_gene.empty and not rep_gene.empty:
        m = dis_gene.merge(rep_gene, on="gene", suffixes=("_dis", "_rep"))
        m["DE_concordant"] = np.sign(m["AD_log2FC_dis"]) == np.sign(m["AD_log2FC_rep"])
        m["Age_concordant"] = np.sign(m["age_spearman_rho_dis"]) == np.sign(m["age_spearman_rho_rep"])
        m["reproducible"] = (
            (m["AD_FDR_dis"] < 0.05) & (m["AD_P_rep"] < 0.05) &
            (m["age_FDR_dis"] < 0.05) & (m["age_P_rep"] < 0.05) &
            m["DE_concordant"] & m["Age_concordant"]
        )
        m["aging_consistent"] = (
            ((m["AD_log2FC_dis"] > 0) & (m["age_spearman_rho_dis"] > 0)) |
            ((m["AD_log2FC_dis"] < 0) & (m["age_spearman_rho_dis"] < 0))
        )
        final = m[m["reproducible"] & m["aging_consistent"]].copy()
        final.to_csv(RESULT_DIR / "SST_AD_aging_genes_reproducible.csv", index=False)
        go_dir = RESULT_DIR / "GO_input_gene_lists"
        go_dir.mkdir(exist_ok=True)
        up = final[(final["AD_log2FC_dis"] > 0) & (final["age_spearman_rho_dis"] > 0)]
        down = final[(final["AD_log2FC_dis"] < 0) & (final["age_spearman_rho_dis"] < 0)]
        pd.Series(sorted(up["gene"].astype(str).unique()), name="gene").to_csv(go_dir / "Inh_SST_AD_up_age_positive.csv", index=False)
        pd.Series(sorted(down["gene"].astype(str).unique()), name="gene").to_csv(go_dir / "Inh_SST_AD_down_age_negative.csv", index=False)

print("NDD cellular-age analysis complete.")
